### What is NumPy? 
#### Numpy is a multi-dimensional array libraly. We can use NumPy to store all of data and one-dimensional array,....etc.
### Application of NumPy
#### Mathematics (MATLAB Replacement)
#### Plotting (Matplotlib)
#### Backend (Pandas, Connect 4, Digital Photography)
#### Machine Learning

In [4]:
import numpy as np

### The Basics

In [5]:
a = np.array([1,2,3],dtype='int32')
print(a)
b = np.array([[8.0,3.0,7.0],[4.0,7.0,9.0]])
print(b)

[1 2 3]
[[8. 3. 7.]
 [4. 7. 9.]]


In [7]:
stats = np.array([[1,2,3],[4,5,6]])
stats
np.min(stats)
np.max(stats, axis=1)
np.sum(stats, axis=0)
### Reorganizing Arrays
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [8]:
## Linear Algebra
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

np.matmul(a,b)
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


1.0