In [10]:

# Get Dimension
a.ndim
b.ndim
# Get shape
a.shape
b.shape
# Get Type
a.dtype
# Get Size
a.itemsize
b.itemsize
# Get tatal size
a.size * a.itemsize
a.nbytes
### Accessing/Changing specific, Rows, Colums,etc
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)
a.shape
# Get a specific element [r,c]
a[1,5]
# Get a specific row
a[0,:]
# Get a specific colume
a[:,2]
# Get a little more fancy [StartindexJ: endindex:stepsize]
a[0,1:-1:2]
a[1,5] = 20
print(a)

a[:,2] = 5
print(a)
### 3-d example
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)
# Get specific element (work outside in)
b[0,1,1]
b[:,1,:]
## Initializing Different Types of Arrays
# All 0s matrix
np.zeros((2,3,3,2))
np.zeros((2,3))
# All 1s matrix
np.ones((4,2,3), dtype="int32")
# Any other number
np.full((2,2),99, dtype='float32')
# Any other number (full_like)
np.full_like(a,4)
# Random decimal number
np.random.rand(2,4)
np.random.random_sample(a.shape)
# Random Integer values
np.random.randint(4,7,size=(3,3))
np.identity(5)
# Repeat on array
arr=np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=0)
print(r1)
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
print(z)
output[1:4,1:4] = z
print(z)
## Be careful when copying arrays!!
a = np.array([1,2,3])
b = a.copy()
b[0]=100
print(a)
## Mathematics
a = np.array([1,2,3])
print(a)
a + 2
a - 2
a * 2
a/3
b = np.array([1,0,1])
a + b
a **2
# Take the sin
np.sin(a)
np.cos(a)


[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[1 2 3]
[1 2 3]


array([ 0.54030231, -0.41614684, -0.9899925 ])

### What is NumPy? 
#### Numpy is a multi-dimensional array libraly. We can use NumPy to store all of data and one-dimensional array,....etc.
### Application of NumPy
#### Mathematics (MATLAB Replacement)
#### Plotting (Matplotlib)
#### Backend (Pandas, Connect 4, Digital Photography)
#### Machine Learning

In [4]:
import numpy as np

### The Basics

In [5]:
a = np.array([1,2,3],dtype='int32')
print(a)
b = np.array([[8.0,3.0,7.0],[4.0,7.0,9.0]])
print(b)

[1 2 3]
[[8. 3. 7.]
 [4. 7. 9.]]


In [7]:
stats = np.array([[1,2,3],[4,5,6]])
stats
np.min(stats)
np.max(stats, axis=1)
np.sum(stats, axis=0)
### Reorganizing Arrays
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [8]:
## Linear Algebra
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

np.matmul(a,b)
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


1.0

In [9]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])
# Horizontal stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))